In [288]:
import pandas as pd
df=pd.read_csv('dataset/iris.csv')
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [219]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [220]:
df['species'].shape

(150,)

In [221]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [289]:
x=df[['sepal_length','sepal_width','petal_length','petal_width']]
x

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [290]:
y=df[['species']]
y

       species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 1 columns]

In [291]:
from sklearn.model_selection import train_test_split

In [292]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [293]:
x_train

     sepal_length  sepal_width  petal_length  petal_width
22            4.6          3.6           1.0          0.2
15            5.7          4.4           1.5          0.4
65            6.7          3.1           4.4          1.4
11            4.8          3.4           1.6          0.2
42            4.4          3.2           1.3          0.2
..            ...          ...           ...          ...
71            6.1          2.8           4.0          1.3
106           4.9          2.5           4.5          1.7
14            5.8          4.0           1.2          0.2
92            5.8          2.6           4.0          1.2
102           7.1          3.0           5.9          2.1

[120 rows x 4 columns]

In [294]:
x_test

     sepal_length  sepal_width  petal_length  petal_width
73            6.1          2.8           4.7          1.2
18            5.7          3.8           1.7          0.3
118           7.7          2.6           6.9          2.3
78            6.0          2.9           4.5          1.5
76            6.8          2.8           4.8          1.4
31            5.4          3.4           1.5          0.4
64            5.6          2.9           3.6          1.3
141           6.9          3.1           5.1          2.3
68            6.2          2.2           4.5          1.5
82            5.8          2.7           3.9          1.2
110           6.5          3.2           5.1          2.0
12            4.8          3.0           1.4          0.1
36            5.5          3.5           1.3          0.2
9             4.9          3.1           1.5          0.1
19            5.1          3.8           1.5          0.3
56            6.3          3.3           4.7          1.6
104           6.5          3.0           5.8          2.2
69            5.6          2.5           3.9          1.1
55            5.7          2.8           4.5          1.3
132           6.4          2.8           5.6          2.2
29            4.7          3.2           1.6          0.2
127           6.1          3.0           4.9          1.8
26            5.0          3.4           1.6          0.4
128           6.4          2.8           5.6          2.1
131           7.9          3.8           6.4          2.0
145           6.7          3.0           5.2          2.3
108           6.7          2.5           5.8          1.8
143           6.8          3.2           5.9          2.3
45            4.8          3.0           1.4          0.3
30            4.8          3.1           1.6          0.2

In [295]:
y_train

        species
22       setosa
15       setosa
65   versicolor
11       setosa
42       setosa
..          ...
71   versicolor
106   virginica
14       setosa
92   versicolor
102   virginica

[120 rows x 1 columns]

In [296]:
y_test

        species
73   versicolor
18       setosa
118   virginica
78   versicolor
76   versicolor
31       setosa
64   versicolor
141   virginica
68   versicolor
82   versicolor
110   virginica
12       setosa
36       setosa
9        setosa
19       setosa
56   versicolor
104   virginica
69   versicolor
55   versicolor
132   virginica
29       setosa
127   virginica
26       setosa
128   virginica
131   virginica
145   virginica
108   virginica
143   virginica
45       setosa
30       setosa

In [297]:
#Apply classification
from sklearn.tree import DecisionTreeClassifier
clf= DecisionTreeClassifier()
clf.fit(x_train,y_train)

DecisionTreeClassifier()

In [231]:
y_pred=clf.predict(x_test)
y_pred

array(['versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'setosa', 'setosa', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa',
       'virginica', 'setosa', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'setosa', 'setosa'], dtype=object)

In [232]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
acc=accuracy_score(y_test,y_pred)
acc

1.0

In [233]:
cm=confusion_matrix(y_test,y_pred)
print('classification_report\n',cm)

classification_report
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

In [234]:
cr=classification_report(y_test,y_pred)
print('classification_report\n',cr)

classification_report
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

In [235]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [236]:
from sklearn.datasets import load_breast_cancer
cancer_data=load_breast_cancer()

In [237]:
cancer_df=pd.DataFrame(cancer_data.data,columns=cancer_data.feature_names)

In [238]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(cancer_df,
                                              cancer_data.target,
                                              test_size=0.33,
                                              random_state=42)

In [239]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [240]:
param_dict={
    "criterion":['gini','entropy'],
    "max_depth":range(1,10),
    "min_samples_split":range(1,10),
    "min_samples_leaf":range(1,5)
}

# GridSearchCV

In [241]:
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(dtc,
                 param_grid=param_dict,
                 cv=10,
                 verbose=1,
                 n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 10 folds for each of 648 candidates, totalling 6480 fits

GridSearchCV(cv=10, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': range(1, 10),
                         'min_samples_leaf': range(1, 5),
                         'min_samples_split': range(1, 10)},
             verbose=1)

In [242]:
grid.best_params_

{'criterion': 'entropy',
 'max_depth': 3,
 'min_samples_leaf': 4,
 'min_samples_split': 3}

In [243]:
grid.best_estimator_

DecisionTreeClassifier(criterion='entropy', max_depth=3, min_samples_leaf=4,
                       min_samples_split=3)

In [244]:
grid.best_score_

0.9474358974358973

# LogisticRegression

In [298]:
#Logistic regression
from sklearn.linear_model import LogisticRegression
log=LogisticRegression()
log.fit(x_train,y_train)

LogisticRegression()

In [299]:
y_pred=log.predict(x_test)
y_pred

array(['versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'setosa', 'setosa', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa',
       'virginica', 'setosa', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'setosa', 'setosa'], dtype=object)

In [300]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy Score=",accuracy_score(y_test,y_pred))

Accuracy Score= 1.0

In [301]:
pd.DataFrame(confusion_matrix(y_test,y_pred))

    0  1   2
0  10  0   0
1   0  9   0
2   0  0  11

In [302]:
result=pd.DataFrame()
result["Actual Label"]=y_test
result["Decision Tree Prediction"]=y_pred
result

    Actual Label Decision Tree Prediction
73    versicolor               versicolor
18        setosa                   setosa
118    virginica                virginica
78    versicolor               versicolor
76    versicolor               versicolor
31        setosa                   setosa
64    versicolor               versicolor
141    virginica                virginica
68    versicolor               versicolor
82    versicolor               versicolor
110    virginica                virginica
12        setosa                   setosa
36        setosa                   setosa
9         setosa                   setosa
19        setosa                   setosa
56    versicolor               versicolor
104    virginica                virginica
69    versicolor               versicolor
55    versicolor               versicolor
132    virginica                virginica
29        setosa                   setosa
127    virginica                virginica
26        setosa                   setosa
128    virginica                virginica
131    virginica                virginica
145    virginica                virginica
108    virginica                virginica
143    virginica                virginica
45        setosa                   setosa
30        setosa                   setosa

# Support Vector Machine

In [303]:
from sklearn.svm import SVC
classifier= SVC()
classifier.fit(x_train,y_train)

SVC()

In [304]:
y_pred=classifier.predict(x_test)
y_pred

array(['versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'setosa', 'setosa', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa',
       'virginica', 'setosa', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'setosa', 'setosa'], dtype=object)

In [305]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy Score=",accuracy_score(y_test,y_pred))

Accuracy Score= 1.0

In [306]:
pd.DataFrame(confusion_matrix(y_test,y_pred))

    0  1   2
0  10  0   0
1   0  9   0
2   0  0  11

In [307]:
result=pd.DataFrame()
result["Actual Label"]=y_test
result["Decision Tree Prediction"]=y_pred
result

    Actual Label Decision Tree Prediction
73    versicolor               versicolor
18        setosa                   setosa
118    virginica                virginica
78    versicolor               versicolor
76    versicolor               versicolor
31        setosa                   setosa
64    versicolor               versicolor
141    virginica                virginica
68    versicolor               versicolor
82    versicolor               versicolor
110    virginica                virginica
12        setosa                   setosa
36        setosa                   setosa
9         setosa                   setosa
19        setosa                   setosa
56    versicolor               versicolor
104    virginica                virginica
69    versicolor               versicolor
55    versicolor               versicolor
132    virginica                virginica
29        setosa                   setosa
127    virginica                virginica
26        setosa                   setosa
128    virginica                virginica
131    virginica                virginica
145    virginica                virginica
108    virginica                virginica
143    virginica                virginica
45        setosa                   setosa
30        setosa                   setosa

# RandomForestClassifier

In [436]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [437]:
y_pred=rfc.predict(x_test)
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1])

In [438]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
acc=accuracy_score(y_test,y_pred)
acc

0.9627659574468085

In [439]:
cr=classification_report(y_test,y_pred)
print("classification report:",cr)

classification report:               precision    recall  f1-score   support

           0       0.95      0.94      0.95        67
           1       0.97      0.98      0.97       121

    accuracy                           0.96       188
   macro avg       0.96      0.96      0.96       188
weighted avg       0.96      0.96      0.96       188

In [440]:
cm=confusion_matrix(y_test,y_pred)
print("confusion matrix:",cm)

confusion matrix: [[ 63   4]
 [  3 118]]

# Using titanic dataset

In [391]:
import pandas as pd
df=pd.read_csv('dataset/titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,NaN,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,NaN,3,"Heikkinen, Miss. Laina",female,NaN,0,0,STON/O2. 3101282,NaN,NaN,S
3,4,NaN,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0.0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1.0,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0.0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1.0,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0.0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [392]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,NaN,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,NaN,3,"Heikkinen, Miss. Laina",female,NaN,0,0,STON/O2. 3101282,NaN,NaN,S
3,4,NaN,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [393]:
df.drop(columns=['Cabin','Name','Sex','Embarked','Ticket'],inplace=True,axis=1)

In [394]:
df

     PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0              1       0.0       3  22.0      1      0   7.2500
1              2       NaN       1  38.0      1      0  71.2833
2              3       NaN       3   NaN      0      0      NaN
3              4       NaN       1  35.0      1      0  53.1000
4              5       0.0       3  35.0      0      0   8.0500
..           ...       ...     ...   ...    ...    ...      ...
886          887       0.0       2  27.0      0      0  13.0000
887          888       1.0       1  19.0      0      0  30.0000
888          889       0.0       3   NaN      1      2  23.4500
889          890       1.0       1  26.0      0      0  30.0000
890          891       0.0       3  32.0      0      0   7.7500

[891 rows x 7 columns]

In [395]:
df.fillna(method='ffill',inplace=True)

In [396]:
df

     PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0              1       0.0       3  22.0      1      0   7.2500
1              2       0.0       1  38.0      1      0  71.2833
2              3       0.0       3  38.0      0      0  71.2833
3              4       0.0       1  35.0      1      0  53.1000
4              5       0.0       3  35.0      0      0   8.0500
..           ...       ...     ...   ...    ...    ...      ...
886          887       0.0       2  27.0      0      0  13.0000
887          888       1.0       1  19.0      0      0  30.0000
888          889       0.0       3  19.0      1      2  23.4500
889          890       1.0       1  26.0      0      0  30.0000
890          891       0.0       3  32.0      0      0   7.7500

[891 rows x 7 columns]

In [397]:
df['Survived'].shape

(891,)

In [398]:
df['Survived'].unique()

array([0., 1.])

In [399]:
x=df[['PassengerId','Pclass','Age','SibSp','Parch','Fare']]
x

     PassengerId  Pclass   Age  SibSp  Parch     Fare
0              1       3  22.0      1      0   7.2500
1              2       1  38.0      1      0  71.2833
2              3       3  38.0      0      0  71.2833
3              4       1  35.0      1      0  53.1000
4              5       3  35.0      0      0   8.0500
..           ...     ...   ...    ...    ...      ...
886          887       2  27.0      0      0  13.0000
887          888       1  19.0      0      0  30.0000
888          889       3  19.0      1      2  23.4500
889          890       1  26.0      0      0  30.0000
890          891       3  32.0      0      0   7.7500

[891 rows x 6 columns]

In [400]:
y=df[['Survived']]
y

     Survived
0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
..        ...
886       0.0
887       1.0
888       0.0
889       1.0
890       0.0

[891 rows x 1 columns]

In [401]:
from sklearn.model_selection import train_test_split

In [402]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [403]:
x_train

     PassengerId  Pclass   Age  SibSp  Parch      Fare
331          332       1  45.5      0      0   28.5000
733          734       2  23.0      0      0   13.0000
382          383       3  32.0      0      0    7.9250
704          705       3  26.0      1      0    7.8542
813          814       3   6.0      4      2   31.2750
..           ...     ...   ...    ...    ...       ...
106          107       3  21.0      0      0    7.6500
270          271       1  35.0      0      0   31.0000
860          861       3  41.0      2      0   14.1083
435          436       1  14.0      1      2  120.0000
102          103       1  21.0      0      1   77.2875

[712 rows x 6 columns]

In [404]:
x_test

     PassengerId  Pclass   Age  SibSp  Parch     Fare
709          710       3  22.0      1      1  15.2458
439          440       2  31.0      0      0  10.5000
840          841       3  20.0      0      0   7.9250
720          721       2   6.0      0      1  33.0000
39            40       3  14.0      1      0  11.2417
..           ...     ...   ...    ...    ...      ...
433          434       3  17.0      0      0   7.1250
773          774       3  57.0      0      0   7.2250
25            26       3  38.0      1      5  31.3875
84            85       2  17.0      0      0  10.5000
10            11       3   4.0      1      1  16.7000

[179 rows x 6 columns]

In [405]:
y_train

     Survived
331       0.0
733       0.0
382       0.0
704       0.0
813       0.0
..        ...
106       1.0
270       0.0
860       0.0
435       1.0
102       0.0

[712 rows x 1 columns]

In [406]:
y_test

     Survived
709       1.0
439       0.0
840       0.0
720       1.0
39        1.0
..        ...
433       0.0
773       0.0
25        1.0
84        1.0
10        1.0

[179 rows x 1 columns]

In [407]:
#Apply classification
from sklearn.tree import DecisionTreeClassifier
clf= DecisionTreeClassifier()
clf.fit(x_train,y_train)

DecisionTreeClassifier()

In [408]:
y_pred=clf.predict(x_test)
y_pred

array([0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1.,
       0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0.,
       1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
       1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1.,
       0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 1.])

In [409]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
acc=accuracy_score(y_test,y_pred)
acc

0.7039106145251397

In [410]:
cm=confusion_matrix(y_test,y_pred)
print('classification_report\n',cm)

classification_report
 [[81 24]
 [29 45]]

In [411]:
cr=classification_report(y_test,y_pred)
print('classification_report\n',cr)

classification_report
               precision    recall  f1-score   support

         0.0       0.74      0.77      0.75       105
         1.0       0.65      0.61      0.63        74

    accuracy                           0.70       179
   macro avg       0.69      0.69      0.69       179
weighted avg       0.70      0.70      0.70       179

# implementation of Hyper parameter turning using GridSearchCv

In [412]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from sklearn.datasets import load_breast_cancer
cancer_data=load_breast_cancer()

In [413]:
cancer_df=pd.DataFrame(cancer_data.data,columns=cancer_data.feature_names)

In [414]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(cancer_df,
                                              cancer_data.target,
                                              test_size=0.33,
                                              random_state=42)

In [415]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [416]:
param_dict={
    "criterion":['gini','entropy'],
    "max_depth":range(1,10),
    "min_samples_split":range(1,10),
    "min_samples_leaf":range(1,5)
}

# GridSearchCV

In [417]:
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(dtc,
                 param_grid=param_dict,
                 cv=10,
                 verbose=1,
                 n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 10 folds for each of 648 candidates, totalling 6480 fits

GridSearchCV(cv=10, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': range(1, 10),
                         'min_samples_leaf': range(1, 5),
                         'min_samples_split': range(1, 10)},
             verbose=1)

In [418]:
grid.best_params_

{'criterion': 'entropy',
 'max_depth': 3,
 'min_samples_leaf': 4,
 'min_samples_split': 2}

In [419]:
grid.best_estimator_

DecisionTreeClassifier(criterion='entropy', max_depth=3, min_samples_leaf=4)

In [420]:
grid.best_score_

0.9500674763832657

# LogisticRegression

In [421]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
log=LogisticRegression()
log.fit(x_train,y_train)

LogisticRegression()

In [422]:
y_pred=log.predict(x_test)
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1])

In [423]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy Score=",accuracy_score(y_test,y_pred))

Accuracy Score= 0.9627659574468085

In [424]:
pd.DataFrame(confusion_matrix(y_test,y_pred))

    0    1
0  64    3
1   4  117

In [425]:
result=pd.DataFrame()
result["Actual Label"]=y_test
result["Decision Tree Prediction"]=y_pred
result

     Actual Label  Decision Tree Prediction
0               1                         1
1               0                         0
2               0                         0
3               1                         1
4               1                         1
..            ...                       ...
183             0                         0
184             0                         0
185             0                         0
186             1                         0
187             1                         1

[188 rows x 2 columns]

# Support Vector Machine

In [426]:
from sklearn.svm import SVC
classifier= SVC()
classifier.fit(x_train,y_train)

SVC()

In [427]:
y_pred=classifier.predict(x_test)
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1])

In [428]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy Score=",accuracy_score(y_test,y_pred))

Accuracy Score= 0.9521276595744681

In [429]:
pd.DataFrame(confusion_matrix(y_test,y_pred))

    0    1
0  59    8
1   1  120

In [430]:
result=pd.DataFrame()
result["Actual Label"]=y_test
result["Decision Tree Prediction"]=y_pred
result

     Actual Label  Decision Tree Prediction
0               1                         1
1               0                         0
2               0                         0
3               1                         1
4               1                         1
..            ...                       ...
183             0                         0
184             0                         0
185             0                         0
186             1                         1
187             1                         1

[188 rows x 2 columns]

# RandomForestClassifier

In [431]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [432]:
y_pred=rfc.predict(x_test)
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1])

In [433]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
acc=accuracy_score(y_test,y_pred)
acc

0.9574468085106383

In [434]:
cm=confusion_matrix(y_test,y_pred)
print("confusionmatrix:",cm)

confusionmatrix: [[ 62   5]
 [  3 118]]

In [435]:
cr=classification_report(y_test,y_pred)
print("classification:",cr)

classification:               precision    recall  f1-score   support

           0       0.95      0.93      0.94        67
           1       0.96      0.98      0.97       121

    accuracy                           0.96       188
   macro avg       0.96      0.95      0.95       188
weighted avg       0.96      0.96      0.96       188